Update tes.yml

diff --git a/.github/workflows/tes.yml b/.github/workflows/tes.yml
--- a/.github/workflows/tes.yml
+++ b/.github/workflows/tes.yml
@@ -677,7 +677,7 @@ jobs:
             fi
              new_name="HOUJIE-WRT_${RELEASES_TAG2}_${replace}_${kernel}_${TUNNEL_OPTION}.img.gz"
             echo -e "${INFO} Renaming: $file → $new_name"
-            mv "$file" "compiled_images/mod/$new_name" || echo -e "${WARNING} Failed to rename $file"
+            mv "$file" "compiled_images/$new_name" || echo -e "${WARNING} Failed to rename $file"
            done
 
            # Process .tar.gz files
@@ -685,7 +685,7 @@ jobs:
             [[ -f "$file" ]] || continue
              new_name="HOUJIE-WRT_${{ env.RELEASES_TAG2 }}_${replace}.tar.gz"
             echo -e "${INFO} Renaming: $file → $new_name"
-            mv "$file" "compiled_images/mod/$new_name" || echo -e "${WARNING} Failed to rename $file"
+            mv "$file" "compiled_images/$new_name" || echo -e "${WARNING} Failed to rename $file"
            done
            done
           echo "status=success" >> ${GITHUB_OUTPUT}
@@ -707,15 +707,10 @@ jobs:
         uses: actions/upload-artifact@v4
         if: success()
         with:
-          name: compiled-${{ matrix.target }}
+          name: Openwrt-${{ matrix.target }}
           path: imagebuilder/compiled_images/*.img.gz
 
-      - name: Upload Artifacts img
-        uses: actions/upload-artifact@v4
-        if: success() 
-        with:
-          name: ${{ matrix.target }}-mod
-          path: imagebuilder/compiled_images/mod/*.img.gz
+      
 
   
   release:
